name: main
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions:
          - stable
          - nightly
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Cache treesitter parsers
        uses: actions/cache@v4
        with:
          path: .tests/site/parser/
          key: ${{ runner.os }}-${{ matrix.nvim-versions }}-parsers-${{ hashFiles('tests/bootstrap.lua', 'tests/setup.lua') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.nvim-versions }}-parsers-

      - name: Test
        run: make test

